### ISSUE TITLE
Unable to change config.root

### ISSUE THREAD

**Issue by ndan** [dry-rb/dry-rails#10]
This https://github.com/dry-rb/dry-system-rails/pull/16 had broken an ability to set `config.root` under rails initializer

```ruby
# config/initializers/system.rb
Dry::System::Rails.container do
  config.root = ::Rails.root.join('app')
end
```

Then run in rails console
```ruby
> MyApp::Container.config.root
=> #<Pathname:/path/to/my_app>

# should be
=> #<Pathname:/path/to/my_app/app>
```

The reason is `default_options` are merged after `container.class_eval(&@container_block)` evaluated.
https://github.com/dry-rb/dry-system-rails/blob/master/lib/dry/system/rails.rb#L43

**Comment by solnic** [comment]
@ndan I moved it to dry-rails as this project is replacing dry-system-rails

**Comment by solnic** [comment]
This has been fixed although I don't think it's a good idea to change the root path, unless you want to completely separate from Rails directory structure.
