### ISSUE TITLE
Import constant name would be configurable

### ISSUE THREAD

**Issue by deepj** [dry-rb/dry-rails#18]
In my current application there is a namespace `Import` living `lib/import`. It has some historical roots and it's not easy to change it. This is unfortunately in conflict with `dry-rails` while booting and failed on `MyApp::Import` cannot be found.

## Examples

```
Dry::Rails.container do
  config.import_constant = 'MyImport'
end
```

## Resources

See discussion at https://twitter.com/deepj/status/1245084341920763909

**Comment by diegotoral** [comment]
Hello everyone!

I forked the repo and started experimenting with patch for this one but I'm not sure how to test it. 🤔

**Comment by timriley** [comment]
FWIW, I'd like our default name for this to eventually become `Deps`, so it's consistent with what we're using for Hanami 2 (or whatever name we decide to settle on, though at this point there's been no objection to `Deps` and I quite like it)

**Comment by solnic** [comment]
@diegotoral take a look how other specs are written and try to do something similar. You can tweak config in a `before(:all) { ... }` hook to set the custom name and then in an example just see if the expected constant is defined.
