### ISSUE TITLE
Confusing docs about throw(:abort)

### ISSUE THREAD

**Issue by jandudulski** [dry-rb/dry-rails#33]
Docs example:

```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action do
    if safe_params && safe_params.failure?
      render(:error, errors: safe_params.errors.to_h) and throw(:abort)
    end
  end
end
```

I'm just starting a new project and giving a try to this feature but I was surprised by `UncaughtThrowError: uncaught throw :abort` error. Digging deeper into Rails docs:

> The method simply stores an error message in the flash and redirects to the login form if the user is not logged in. If a "before" filter renders or redirects, the action will not run. If there are additional filters scheduled to run after that filter, they are also cancelled.

AFAIK `throw(:abort)` is only about ActiveRecord callbacks, not controller filters (aka before/after action). Actually, link about the feature from dry-rails docs also discusses only callbacks.

**Comment by solnic** [comment]
@jandudulski what's The Right Way™ then?

**Comment by jandudulski** [comment]
Well, as Rails docs says - when filter renders something, than everything further is canceled. So the example should look like this:

```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action do
    if safe_params && safe_params.failure?
      render(:error, errors: safe_params.errors.to_h)
    end
  end
end
```

**Comment by solnic** [comment]
@jandudulski OK but what about cases when you don't render anything?

**Comment by jandudulski** [comment]
@solnic you always want to either render a response or redirect. I don't think there is another option for a controller action.
