### ISSUE TITLE
Dry-Rails + ActionController::API

### ISSUE THREAD

**Issue by rinaldifonseca** [dry-rb/dry-rails#35]
Since dry-rails include controller only in the ApplicationController, it's not possible to use safe_params and other methods if you are working in a Rails API when your controller inherits from ActionController::API. 
@solnic said that this should be supported OOTB.

Maybe:

```ruby
start do
  ActionController::Base.include(Dry::Rails::Features::ControllerHelpers)
  ActionController::API.include(Dry::Rails::Features::ControllerHelpers)
end
```

**Comment by rinaldifonseca** [comment]
Hey @solnic,

Could you give me some path in order create a PR to implement this? =)

**Comment by solnic** [comment]
@rinaldifonseca hey! Sure, I believe all we gotta do is to add something like this to all relevant boot files:

```ruby
start do
  # other stuff

  ActionController::API.include(Dry::Rails::Features::ControllerHelpers) if defined?(ActionController::API)
end
```

The trick is that `ActionController::API` may not be loaded at this point of the booting process, so I'm actually not sure how to verify *when* exactly we want to add the features to `ActionController::API`. Maybe there's a way to check it via Rails configuration, I've no idea 😅

**Comment by rinaldifonseca** [comment]
Hi @solnic 

The only config option I found about API was config.api_only = true 
But since ActionController::API is under actionpack, it will always be defined and loaded if the Rails version is greater then 5.
