### ISSUE TITLE
Add application template

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-rails#5]
The gem should provide a rails application template that would simply provide the following things:

* `Gemfile` should include `dry-rails` with the current version
* `config/initializers/system.rb` should be created with the following content for a good start:
   ```ruby
   Dry::Rails.container do
     # cherry-pick features
     config.features = %i[application_contract]

     # enable auto-registration in the lib dir
     # config.auto_register << 'lib'

     # enable auto-registration of custom components
     # auto_register!('app/serializers', strategy: :namespaced)
   en
   ```
* ...more?

**Comment by citizen428** [comment]
Here's a `template.rb` that does what you describe above:

```ruby
gem 'dry_rails', '~> 0.6'

initializer 'system.rb', <<-CODE
  Dry::Rails.container do
    # cherry-pick features
    config.features = %i[application_contract]

    # enable auto-registration in the lib dir
    # config.auto_register << 'lib'

    # enable auto-registration of custom components
    # auto_register!('app/serializers', strategy: :namespaced)
  end
CODE
```

The question is if we only want to keep this inside the gem or also host it publicly on dry-rb.org so people can do this:

```sh
rails new my-app -m https://dry-rb.org/template.rb
```

**Comment by citizen428** [comment]
This `template.rb` does what you describe above (well, it just uses a GH source since the gem has not been released yet):

```ruby
gem 'dry-rails', github: 'dry-rb/dry-rails'

initializer 'system.rb', <<-CODE
  Dry::Rails.container do
    # cherry-pick features
    config.features = %i[application_contract]

    # enable auto-registration in the lib dir
    # config.auto_register << 'lib'

    # enable auto-registration of custom components
    # auto_register!('app/serializers', strategy: :namespaced)
  end
CODE
```

Ideally this would also be hosted as something like https://dry-rb.org/template.rb, so people can do 

```sh
rails new my_app -m https://dry-rb.org/template.rb
```

**Comment by solnic** [comment]
@citizen428 oh that is simple! so, I think it should be versioned and part of this repo, we will simply deploy it to dry-rb.org through a github action. So please feel free to open a PR and it'll be a great start.
