### ISSUE TITLE
Please update `dry-system` to `~> 1.0`

### ISSUE THREAD

**Issue by oskargargas** [dry-rb/dry-rails#58]
## Describe the bug

`dry-rails` requires `dry-system` in `~> 0.27` [version](https://github.com/dry-rb/dry-rails/blob/main/dry-rails.gemspec#L33).
```ruby
spec.add_runtime_dependency "dry-system", "~> 0.27", ">= 0.27.2"
```
There is a bug in `dry-logic` < 1.5 which crashes irb/rails console. And to use `dry-logic` 1.5 we need `dry-system` `~> 1.0`...

**Comment by solnic** [comment]
Done in 0.7.0
